/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;
import Model.*;
/**
 *
 * @author vraosharma
 */
public class MainJFrame extends javax.swing.JFrame {
    Application app;
    
    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.app = new Application();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        ControlPanel = new javax.swing.JPanel();
        createObsButton = new javax.swing.JButton();
        viewVitalBtn = new javax.swing.JButton();
        medicineCatBtn = new javax.swing.JButton();
        assignMedBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ControlPanel.setBackground(new java.awt.Color(153, 255, 153));
        ControlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createObsButton.setText("Create Obs");
        createObsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createObsButtonActionPerformed(evt);
            }
        });
        ControlPanel.add(createObsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        viewVitalBtn.setText("View Vital Sign");
        viewVitalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVitalBtnActionPerformed(evt);
            }
        });
        ControlPanel.add(viewVitalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        medicineCatBtn.setText("Medicine Catalog");
        medicineCatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineCatBtnActionPerformed(evt);
            }
        });
        ControlPanel.add(medicineCatBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        assignMedBtn.setText("Assign Med");
        assignMedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignMedBtnActionPerformed(evt);
            }
        });
        ControlPanel.add(assignMedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jSplitPane1.setLeftComponent(ControlPanel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createObsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createObsButtonActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new CreateObs(this.app));
    }//GEN-LAST:event_createObsButtonActionPerformed

    private void viewVitalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVitalBtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new ViewPanel(this.app));
    }//GEN-LAST:event_viewVitalBtnActionPerformed

    private void medicineCatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineCatBtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new CatalogPanel(this.app));
    }//GEN-LAST:event_medicineCatBtnActionPerformed

    private void assignMedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignMedBtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new AssignPanel(this.app));
    }//GEN-LAST:event_assignMedBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JButton assignMedBtn;
    private javax.swing.JButton createObsButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton medicineCatBtn;
    private javax.swing.JButton viewVitalBtn;
    // End of variables declaration//GEN-END:variables
}
